name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk python3-pip
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Create buildozer.spec
        run: |
          printf "[app]\n\
title = SBJ_for_JOLA\n\
package.name = jola123jola\n\
package.domain = org.example\n\
source.dir = .\n\
source.include_exts = py,html,css,js,mp3,jpg,png\n\
version = 1.0\n\
requirements = python3,kivy\n\
orientation = portrait\n\
fullscreen = 1\n\
\n\
[buildozer]\n\
log_level = 2\n\
warn_on_root = 1\n" > buildozer.spec

      - name: Add dummy main.py
        run: echo 'print("hello")' > main.py

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: sbj_apk
          path: bin/*.apk
